### PR TITLE
Update client.py, UserMethodsMixin, def create_user

### PR DESCRIPTION
**Pull request by Skrapshaku**
I updated UserMethodsMixin, definition create_user.
**As-Is**: 'notMinor': 'yes' if _agree_terms_of_service_ is True else 'no'
**Changed-To**: 'notMinor': 'yes' if _not_minor_ is True else 'no'.

### CODE REVIEW

**Comment by heavenshell** [comment]
@Skrapshaku 
Thank you for sending PR.
Looks good to me, but please add tests for related PR.

**Comment by Skrapshaku** [comment]
@heavenshell good afternoon.
Apologies if I misunderstood your request, I created a new test inside the test_pixela.py to check the 'not_minor' change. I hope this was what you expected.

**Comment by heavenshell** [comment]
@Skrapshaku Thank you for adding tests!
I'll check it tomrrow(Current time is Midnight 😉

**Comment by Skrapshaku** [comment]
Thank you.
Last modifications were needed for the auto-tests as the text returned from API is different.
Apologies and thanks again.

**Review by heavenshell — APPROVED** [review]
Thank you!

**Comment by heavenshell** [comment]
@Skrapshaku 
Hello, I've upload v1.3.0 to pypi 🚀

**Pull request merged**
